apiVersion: v1
kind: Secret
metadata:
  name: region-service
  namespace: northwind
type: Opaque
stringData:
  logging-dir: /var/log/region-service/region-service.log
  env: production
  testing: "false"
data:
  database-uri: cG9zdGdyZXMrcHN5Y29wZzI6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0ByZWdpb24tc2VydmljZS1kYjo4MDAxL3JlZ2lvbnNfZGIK
  database-user: cG9zdGdyZXMK
  database-password: cG9zdGdyZXMK

