apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db-volume
  labels:
    app: keycloak-db
spec:
  capacity:
    storage: "1Gi"
  hostPath:
    path: "/home/.data/.keycloak-db"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-volume-claim
  labels:
    app: keycloak-db
spec:
  volumeMode: Filesystem
  resources:
    requests: 
      storage: "1Gi"
  accessModes:
    - ReadWriteMany
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      volumes:
        - name: keycloak-db-volume
          persistentVolumeClaim:
            claimName: keycloak-db-volume-claim
      containers:
      - name: keycloak-db
        image: postgres:13.1-alpine
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: keycloakDbUser
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: keycloakDbPassword
                name: keycloak-secret
          - name: POSTGRES_DB
            value: keycloak
        volumeMounts:
          - name: keycloak-db-volume
            mountPath: "/var/lib/postgresql/data"
        resources:
          limits:
            memory: "1G"
            cpu: "1000m"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  selector:
    app: keycloak-db
  ports:
  - port: 5432
    targetPort: 5432
